extends Node2D

var lab = preload("res://menu_screen/credits/CreditText.tscn")
var lines = [
"AsterRoll",
"     game idea: ryan carroll, joseph kunsman, and dudley girard - game dev club",
"       ",
"image resources:",
"     small enemy asteroid: phaelax - opengameart.org",
"     game and menu screen background: author: luminous dragon games - opengameart.org",
"     player: author: gameartforge - opengameart.org",
"     large asteroid: jan molina - game dev club",
"     star image: author: Écrivain - opengameart.org",
"     Rubble Pile Image: Opengameart.org",
"     Major Resources Images: Noah Goodman - Game Dev Club",
"     Alien Mining Ship and Missiles: Noah Goodman - Game Dev Club",
"music and sound effects: ",
"     Rock rollin on rock sound effect: Dmunk - freesound.org",
"     Background Music: Jan Molina - Game Dev Club",
"user interface: ",
"     Menu Screen: Tyler Forrester, Jan Molina, and Dudley Girard - Game Dev Club",
"     Game Screen: Dudley Girard and Joseph Kunsman - Game Dev Club",
"     Equinox Typeface Font: Dafont - Dafontfree.io",
"game coding: ",
"     Resource Gathering: Dudley Girard and Joseph Kunsman - Game Dev Club",
"     Player Movement and Controls: Dudley Girard and Ryan Carroll - Game Dev Club",
"     Game Screen Background: Dudley Girard - Game Dev Club",
"     Universe Creation: Dudley Girard - Game Dev Club",
"     Transport Portals: Dudley Girard, Joseph Kunsman, and Ryan Carroll",
"     Tutorial: Dudley Girard and Joseph Kunsman - Game Dev Club",
"     Alien Mining Ship: Tyler Forrester Game Dev Club"
]
var frameCount = 0
var count = 0
onready var timer = get_node("Timer")

# Called when the node enters the scene tree for the first time.
func _ready():
	add_credit(lines[0])
	timer.start() #Timer is set to keep looping

func add_credit(credit) :
	var l = lab.instance()
	l.get_node("Label").autowrap = true
	if credit.left(5) == "     " :
		l.get_node("Label").text = credit.right(5).to_lower()
		l.set_position(Vector2(60,400))
	else :
		l.get_node("Label").text = credit
		l.set_position(Vector2(40,400))
	add_child(l)

#Generated by the Timer attached to the Credits scene
func _on_Timer_timeout():
	if(count < lines.size()-1):
		count += 1
		add_credit(lines[count])
		if count == lines.size() - 1 :
			count = -1
